services:
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visits_app
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    restart: on-failure
    depends_on:
      - redis-server

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: on-failure
    depends_on:
      - app

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visits_tests
    volumes:
      - .:/app
    command: ["pytest", "-v", "--disable-warnings"]
    depends_on:
      - app
      - redis-server